default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
  connect_timeout: 15
  encoding: unicode
  sslmode: <%= ENV['DB_SSLMODE'] || "prefer" %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'project-logger-development' } %>
  username: <%= ENV.fetch('DB_USER') { '' } %>
  password: <%= ENV.fetch('DB_PASS') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { '' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'project-logger-test' } %>
  username: <%= ENV.fetch('DB_USER') { '' } %>
  password: <%= ENV.fetch('DB_PASS') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { '' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'project-logger-production' } %>
  username: <%= ENV.fetch('DB_USER') { '' } %>
  password: <%= ENV.fetch('DB_PASS') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { '' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
